# 0 Preprocesing

## 0.1 Daten laden

In [1]:
import pandas as pd

In [3]:
# df_full = pd.read_excel('ground_truth_filtered.xlsx')
df_LLM = pd.read_excel('titelannotationen_gesamt_normalisiert.xlsx')

In [4]:
df_LLM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7776 entries, 0 to 7775
Data columns (total 18 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   row_id                                         7776 non-null   int64
 1   article_id                                     7776 non-null   object
 2   Headline_GER                                   7776 non-null   object
 3   Language                                       7776 non-null   object
 4   Economic                                       7776 non-null   int64
 5   Capacity and resources                         7776 non-null   int64
 6   Morality                                       7776 non-null   int64
 7   Fairness and equality                          7776 non-null   int64
 8   Legality, constitutionality and jurisprudence  7776 non-null   int64
 9   Policy prescription and evaluation             7776 non-null   int64
 10  Crime and punishment                           7776 non-null   int64
 11  Security and defense                           7776 non-null   int64
 12  Health and safety                              7776 non-null   int64
 13  Quality of life                                7776 non-null   int64
 14  Cultural identity                              7776 non-null   int64
 15  Public opinion                                 7776 non-null   int64
 16  Political                                      7776 non-null   int64
 17  External regulation and reputation             7776 non-null   int64
dtypes: int64(15), object(3)
memory usage: 1.1+ MB

## 0.2 Neue Spalte: 'other'

In [5]:
cols = df_LLM.columns[4:]

df_LLM15 = df_LLM.copy()

df_LLM15['other'] = (
    df_LLM15[cols]
    .eq(0)
    .all(axis=1)
    .astype(int)
)

In [6]:
df_LLM15['other'].value_counts()

other
1    5284
0    2492
Name: count, dtype: int64

In [7]:
df_LLM15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7776 entries, 0 to 7775
Data columns (total 19 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   row_id                                         7776 non-null   int64
 1   article_id                                     7776 non-null   object
 2   Headline_GER                                   7776 non-null   object
 3   Language                                       7776 non-null   object
 4   Economic                                       7776 non-null   int64
 5   Capacity and resources                         7776 non-null   int64
 6   Morality                                       7776 non-null   int64
 7   Fairness and equality                          7776 non-null   int64
 8   Legality, constitutionality and jurisprudence  7776 non-null   int64
 9   Policy prescription and evaluation             7776 non-null   int64
 10  Crime and punishment                           7776 non-null   int64
 11  Security and defense                           7776 non-null   int64
 12  Health and safety                              7776 non-null   int64
 13  Quality of life                                7776 non-null   int64
 14  Cultural identity                              7776 non-null   int64
 15  Public opinion                                 7776 non-null   int64
 16  Political                                      7776 non-null   int64
 17  External regulation and reputation             7776 non-null   int64
 18  other                                          7776 non-null   int64
dtypes: int64(16), object(3)
memory usage: 1.1+ MB

## 0.3 LLM Daten filtern
Generally keep all rows when 'other' == 0. When 'other' == 1, only keep rows, where 'Language' is 'chn' or 'ger'

In [8]:
df_LLM15 = df_LLM15[
    (df_LLM15['other'] == 0) |
    df_LLM15['Language'].isin(['ge', 'chn'])
]

In [9]:
# check if filtering worked:
df_LLM15['other'].value_counts()

other
0    2492
1      98
Name: count, dtype: int64

In [10]:
df_LLM15.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2590 entries, 0 to 7773
Data columns (total 19 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   row_id                                         2590 non-null   int64
 1   article_id                                     2590 non-null   object
 2   Headline_GER                                   2590 non-null   object
 3   Language                                       2590 non-null   object
 4   Economic                                       2590 non-null   int64
 5   Capacity and resources                         2590 non-null   int64
 6   Morality                                       2590 non-null   int64
 7   Fairness and equality                          2590 non-null   int64
 8   Legality, constitutionality and jurisprudence  2590 non-null   int64
 9   Policy prescription and evaluation             2590 non-null   int64
 10  Crime and punishment                           2590 non-null   int64
 11  Security and defense                           2590 non-null   int64
 12  Health and safety                              2590 non-null   int64
 13  Quality of life                                2590 non-null   int64
 14  Cultural identity                              2590 non-null   int64
 15  Public opinion                                 2590 non-null   int64
 16  Political                                      2590 non-null   int64
 17  External regulation and reputation             2590 non-null   int64
 18  other                                          2590 non-null   int64
dtypes: int64(16), object(3)
memory usage: 404.7+ KB

In [20]:
dist_overview = (
df_LLM15.iloc[:, 4:]
.sum()
.div(df_LLM15.iloc[:, 4:].sum().sum())
.mul(100)
.round(2)
.sort_values()
)

dist_overview

Quality of life                                   1.00
Cultural identity                                 1.29
Public opinion                                    1.39
Fairness and equality                             1.71
other                                             3.16
Capacity and resources                            4.19
Morality                                          4.54
Health and safety                                 5.12
Crime and punishment                              5.54
Economic                                          6.99
Security and defense                              8.06
External regulation and reputation                9.38
Political                                        13.02
Legality, constitutionality and jurisprudence    16.92
Policy prescription and evaluation               17.69
dtype: float64

## 0.4 Sprachspezifische Daten erstellen

In [ ]:
df_LLM15['Language'].unique()

array(['chn', 'english_mfc', 'en', 'fr', 'ge', 'it', 'po'], dtype=object)

In [ ]:
df_LLM15.columns

Index(['row_id', 'article_id', 'Headline_GER', 'Language', 'Economic',
       'Capacity and resources', 'Morality', 'Fairness and equality',
       'Legality, constitutionality and jurisprudence',
       'Policy prescription and evaluation', 'Crime and punishment',
       'Security and defense', 'Health and safety', 'Quality of life',
       'Cultural identity', 'Public opinion', 'Political',
       'External regulation and reputation', 'other'],
      dtype='object')

In [ ]:
# ---- NORMAL TRAINING LOOPS
# GER
# df_full_ger = df_full[df_full['Language']=='ge'].drop(columns='Language')
df_LLM_ger = df_LLM15[df_LLM15['Language']=='ge'].drop(columns=['row_id', 'article_id', 'Language'])

# EUR minus GER
# df_full_eur = df_full[df_full['Language']!='ge'].drop(columns='Language')
df_LLM_eur_minus = df_LLM15[~df_LLM15['Language'].isin(['ge', 'chn', 'english_mfc'])].drop(columns=['row_id', 'article_id', 'Language'])

# EUR plus GER
# df_full_eur = df_full[df_full['Language']!='ge'].drop(columns='Language')
df_LLM_eur_plus = df_LLM15[~df_LLM15['Language'].isin(['chn', 'english_mfc'])].drop(columns=['row_id', 'article_id', 'Language'])

# all EUR and MFC
# df_full_eur = df_full[df_full['Language']!='ge'].drop(columns='Language')
df_LLM_eur_mfc = df_LLM15[~df_LLM15['Language'].isin(['chn'])].drop(columns=['row_id', 'article_id', 'Language'])

# all EUR and CHN
# df_full_eur = df_full[df_full['Language']!='ge'].drop(columns='Language')
df_LLM_eur_chn = df_LLM15[~df_LLM15['Language'].isin(['english_mfc'])].drop(columns=['row_id', 'article_id', 'Language'])

# complete dataset
# df_full_eur = df_full[df_full['Language']!='ge'].drop(columns='Language')
df_LLM_comp = df_LLM15.drop(columns=['row_id', 'article_id', 'Language'])

# ---- TRANSFER TRAINING LOOPS
# all minus GER & MFC & CHN
df_LLM_ex_GerChnMFC = df_LLM15[~df_LLM15['Language'].isin(['ge', 'english_mfc', 'chn'])].drop(columns=['row_id', 'article_id', 'Language'])

# all minus GER & MFC
df_LLM_ex_GerMFC = df_LLM15[~df_LLM15['Language'].isin(['ge', 'english_mfc'])].drop(columns=['row_id', 'article_id', 'Language'])

# all minus GER & CHN
df_LLM_ex_GerChn = df_LLM15[~df_LLM15['Language'].isin(['ge', 'chn'])].drop(columns=['row_id', 'article_id', 'Language'])

# all minus GER
df_LLM_ex_Ger = df_LLM15[~df_LLM15['Language'].isin(['ge'])].drop(columns=['row_id', 'article_id', 'Language'])

In [ ]:
print('---- Normal Training Data')
print(f'GER: {len(df_LLM_ger)}')
print(f'EUR minus: {len(df_LLM_eur_minus)}')
print(f'EUR plus: {len(df_LLM_eur_plus)}')
print(f'EUR & MFC: {len(df_LLM_eur_mfc)}')
print(f'EUR & CHN: {len(df_LLM_eur_chn)}')
print(f'complete: {len(df_LLM_comp)}')
print('---- Transfer Training Data')
print(f'All minus GER & CHN & MFC: {len(df_LLM_ex_GerChnMFC)}')
print(f'All minus GER & MFC: {len(df_LLM_ex_GerMFC)}')
print(f'All minus GER & CHN: {len(df_LLM_ex_GerChn)}')
print(f'All minus GER: {len(df_LLM_ex_Ger)}')

---- Normal Training Data
GER: 177
EUR minus: 819
EUR plus: 996
EUR & MFC: 2279
EUR & CHN: 1307
complete: 2590
---- Transfer Training Data
All minus GER & CHN & MFC: 819
All minus GER & MFC: 1130
All minus GER & CHN: 2102
All minus GER: 2413

# 1 Fine Tuning

In [ ]:
!pip install iterative-stratification

Collecting iterative-stratification
  Downloading iterative_stratification-0.1.9-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from iterative-stratification) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from iterative-stratification) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from iterative-stratification) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->iterative-stratification) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->iterative-stratification) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn->iterative-stratification) (3.1.2)
Downloading iterative_stratification-0.1.9-py3-none-any.whl (8.5 kB)
Installing collected packages: iterative-stratification
Successfully installed iterative-stratification-0.1.9

In [ ]:
import random
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, precision_score, recall_score
from transformers import AutoConfig, AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from transformers import EvalPrediction
from datasets import Dataset, DatasetDict

# 1. Python RNG
random.seed(42)

# 2. NumPy RNG
np.random.seed(42)

# 3. PyTorch RNG (CPU)
torch.manual_seed(42)

# 4. PyTorch RNG (GPU)
torch.cuda.manual_seed(42)
torch.cuda.manual_seed_all(42)

# 5. cuDNN determinism
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# 6. HF Transformers (Trainer)
from transformers import set_seed
set_seed(42)

## 1.1 Modell-Spezifikationen

### 1.1.1 Stabile Hyperparamter

In [ ]:
model_id = "LSX-UniWue/ModernGBERT_134M"

tokenizer = AutoTokenizer.from_pretrained(model_id)

def tokenize_function(examples):
    # Truncate and pad to a standard max length for headlines
    return tokenizer(examples[text_col], padding="max_length", truncation=True, max_length=128)

config = AutoConfig.from_pretrained(model_id)

config.hidden_dropout_prob = 0.10          # Encoder hidden dropout
config.attention_probs_dropout_prob = 0.10 # Attention dropout
config.classifier_dropout_prob = 0.20      # Classification-head dropout

config.problem_type = "multi_label_classification"

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.14k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/729k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/693 [00:00<?, ?B/s]

### 1.1.2 Funktion für Berechnung der Metriken

In [ ]:
def compute_metrics(p: EvalPrediction):
    predictions = p.predictions[0] if isinstance(p.predictions, tuple) else p.predictions
    labels = p.label_ids

    # Apply sigmoid since it's a multi-label setup
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))

    # Apply a 0.5 threshold to convert probabilities to binary predictions
    y_pred = np.zeros(probs.shape)
    y_pred[np.where(probs >= 0.5)] = 1

    # Overall aggregate metrics
    f1_micro = f1_score(y_true=labels, y_pred=y_pred, average='micro')
    f1_macro = f1_score(y_true=labels, y_pred=y_pred, average='macro', zero_division=0)
    precision = precision_score(y_true=labels, y_pred=y_pred, average='macro', zero_division=0)
    recall = recall_score(y_true=labels, y_pred=y_pred, average='macro', zero_division=0)
    accuracy = accuracy_score(y_true=labels, y_pred=y_pred)

    metrics = {
        'f1_micro': f1_micro,
        'f1_macro': f1_macro,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall
    }

    # Per-label metrics (returns array of shape [num_labels])
    f1_per_label = f1_score(y_true=labels, y_pred=y_pred, average=None, zero_division=0)

    label_names = [f"label_{i}" for i in range(labels.shape[1])]

    for name, f1 in zip(label_names, f1_per_label):
        metrics[f'f1_{name}'] = float(f1)

    return metrics

### 1.1.3 Trainer Setup

In [ ]:
general_training_args = {
    "eval_strategy": "epoch",
    "save_strategy": "epoch",
    "learning_rate": 1e-5,
    "per_device_train_batch_size": 16,
    "per_device_eval_batch_size": 16,
    "num_train_epochs": 10,
    "weight_decay": 0.05,
    "load_best_model_at_end": True,
    "metric_for_best_model": "f1_macro",
    "logging_steps": 50,

    # Disk space optimization
    "save_total_limit": 2,
    "save_only_model": True,
}

## 1.2 German: Volltext- vs. Titelannotation

### 1.2.1 Volltext-Annotation

In [ ]:
# df_full_ger = df_full[df_full['Language']=='ge'].drop(columns='Language')

In [ ]:
# df_full_ger.head(3)

In [ ]:
# # Define the text column and extract the label columns
# text_col = 'Headline_GER'
# label_cols = [col for col in df_full_ger.columns if col != text_col]

In [ ]:
# Y = df_full_ger[label_cols].values

# # FIRST SPLIT: 80% Train, 20% Rest
# msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
# train_idx, rest_idx = next(msss1.split(df_full_ger, Y))

# train_df = df_full_ger.iloc[train_idx].copy()
# rest_df = df_full_ger.iloc[rest_idx].copy()
# Y_rest = Y[rest_idx]

# # SECOND SPLIT: Split Rest into 12% Dev / 8% Test
# msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
# dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

# dev_df = rest_df.iloc[dev_sub_idx].copy()
# test_df = rest_df.iloc[test_sub_idx].copy()

# # View
# print(f"Train size: {len(train_df)}")
# print(f"Dev size:   {len(dev_df)}")
# print(f"Test size:  {len(test_df)}")

In [ ]:
# # Convert individual binary columns into a single float list per row
# for split_df in [train_df, dev_df, test_df]:
#     split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# # Create  DatasetDict
# dataset = DatasetDict({
#     'train': Dataset.from_pandas(train_df, preserve_index=False),
#     'dev': Dataset.from_pandas(dev_df, preserve_index=False),
#     'test': Dataset.from_pandas(test_df, preserve_index=False)
# })

In [ ]:
# # Varying Hyerparameters
# tokenized_datasets = dataset.map(tokenize_function, batched=True)
# num_labels = len(label_cols)
# config.num_labels = num_labels

In [ ]:
# # Load the model with the modified configuration
# def new_model_init():
#     print("Initializing new model")
#     return AutoModelForSequenceClassification.from_pretrained(
#         model_id,
#         config=config
#     )

# trainer = Trainer(
#     model_init=new_model_init,
#     args=training_args,
#     train_dataset=tokenized_datasets["train"],
#     eval_dataset=tokenized_datasets["dev"],
#     compute_metrics=compute_metrics
# )

In [ ]:
# # Execute the training loop
# trainer.train()

In [ ]:
# Reset Accelerator state to fix the AttributeError
# from accelerate.state import AcceleratorState
# AcceleratorState._reset_state()

In [ ]:
# # Final evaluation against the unseen test set
# print("\n--- Final Test Set Evaluation ---")
# test_results = trainer.evaluate(tokenized_datasets["test"])
# print(test_results)

### 1.2.2 Titel-Annotation (LLM)

In [ ]:
# df_LLM_ger = df_LLM[df_LLM['Language']=='ge'].drop(columns=[
#     'Language',
#     # Labels
#     'Quality of life',
#     'Capacity and resources',
#     'Fairness and equality',
#     'Public opinion',
#     'Cultural identity',
#     'Policy prescription and evaluation'])

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_LLM-GER",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
df_LLM_ger.head()

,Headline_GER,Economic,Capacity and resources,Morality,Fairness and equality,"Legality, constitutionality and jurisprudence",Policy prescription and evaluation,Crime and punishment,Security and defense,Health and safety,Quality of life,Cultural identity,Public opinion,Political,External regulation and reputation,other
7106,Arbeitskampf gegen Amazon: Die Unsichtbaren au...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7107,"""CO₂-Kompensieren löst das Problem nicht""",0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7108,Comeback für Klimakiller,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7109,Pokern ohne As im Ärmel,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7110,Teil staatlicher Politik,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_ger.columns if col != text_col]

In [ ]:
Y = df_LLM_ger[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_idx, rest_idx = next(msss1.split(df_LLM_ger, Y))

train_df = df_LLM_ger.iloc[train_idx].copy()
rest_df = df_LLM_ger.iloc[rest_idx].copy()
Y_rest = Y[rest_idx]

# SECOND SPLIT: Split Rest into 12% Dev / 8% Test
msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

dev_df = rest_df.iloc[dev_sub_idx].copy()
test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 141
Dev size:   22
Test size:  14

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/141 [00:00<?, ? examples/s]

Map:   0%|          | 0/22 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
def new_model_init():
    print("Initializing new model")
    return AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    )

trainer = Trainer(
    model_init=new_model_init,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=90, training_loss=0.18408127890692816, metrics={'train_runtime': 148.0521, 'train_samples_per_second': 9.524, 'train_steps_per_second': 0.608, 'total_flos': 120127966272000.0, 'train_loss': 0.18408127890692816, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.40787050127983093, 'eval_f1_micro': 0.35, 'eval_f1_macro': 0.06666666666666667, 'eval_accuracy': 0.21428571428571427, 'eval_precision': 0.052991452991453, 'eval_recall': 0.09047619047619047, 'eval_f1_label_0': 0.0, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.0, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.0, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.0, 'eval_f1_label_7': 0.0, 'eval_f1_label_8': 0.4, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.0, 'eval_f1_label_13': 0.0, 'eval_f1_label_14': 0.6}

## 1.3 Europe minus Germany: Volltext vs. Titel

### 1.3.1 Volltext

In [ ]:
# df_full_eur = df_full[df_full['Language']!='ge'].drop(columns='Language')

In [ ]:
# df_full_eur.head(3)

In [ ]:
# # Define the text column and extract the label columns
# text_col = 'Headline_GER'
# label_cols = [col for col in df_full_eur.columns if col != text_col]

In [ ]:
# Y = df_full_eur[label_cols].values

# # FIRST SPLIT: 80% Train, 20% Rest
# msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
# train_idx, rest_idx = next(msss1.split(df_full_eur, Y))

# train_df = df_full_eur.iloc[train_idx].copy()
# rest_df = df_full_eur.iloc[rest_idx].copy()
# Y_rest = Y[rest_idx]

# # SECOND SPLIT: Split Rest into 12% Dev / 8% Test
# msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
# dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

# dev_df = rest_df.iloc[dev_sub_idx].copy()
# test_df = rest_df.iloc[test_sub_idx].copy()

# # View
# print(f"Train size: {len(train_df)}")
# print(f"Dev size:   {len(dev_df)}")
# print(f"Test size:  {len(test_df)}")

In [ ]:
# # Convert individual binary columns into a single float list per row
# for split_df in [train_df, dev_df, test_df]:
#     split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# # Create  DatasetDict
# dataset = DatasetDict({
#     'train': Dataset.from_pandas(train_df, preserve_index=False),
#     'dev': Dataset.from_pandas(dev_df, preserve_index=False),
#     'test': Dataset.from_pandas(test_df, preserve_index=False)
# })

In [ ]:
# # Varying Hyerparameters
# tokenized_datasets = dataset.map(tokenize_function, batched=True)
# num_labels = len(label_cols)
# config.num_labels = num_labels

In [ ]:
# # Load the model with the modified configuration
# def new_model_init():
#     print("Initializing new model")
#     return AutoModelForSequenceClassification.from_pretrained(
#         model_id,
#         config=config
#     )

# trainer = Trainer(
#     model_init=new_model_init,
#     args=training_args,
#     train_dataset=tokenized_datasets["train"],
#     eval_dataset=tokenized_datasets["dev"],
#     compute_metrics=compute_metrics
# )

In [ ]:
# # Execute the training loop
# trainer.train()

In [ ]:
# # Final evaluation against the unseen test set
# print("\n--- Final Test Set Evaluation ---")
# test_results = trainer.evaluate(tokenized_datasets["test"])
# print(test_results)

### 1.3.2 Titel

In [ ]:
# df_LLM_eur = df_LLM[df_LLM['Language']!='ge'].drop(columns=[
#     'Language',
#     # Labels
#     'Quality of life',
#     'Capacity and resources',
#     'Fairness and equality',
#     'Public opinion',
#     'Cultural identity',
#     'Policy prescription and evaluation'])

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_LLM-EURminus",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_eur_minus.columns if col != text_col]

In [ ]:
Y = df_LLM_eur_minus[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_idx, rest_idx = next(msss1.split(df_LLM_eur_minus, Y))

train_df = df_LLM_eur_minus.iloc[train_idx].copy()
rest_df = df_LLM_eur_minus.iloc[rest_idx].copy()
Y_rest = Y[rest_idx]

# SECOND SPLIT: Split Rest into 12% Dev / 8% Test
msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

dev_df = rest_df.iloc[dev_sub_idx].copy()
test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 652
Dev size:   98
Test size:  69

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/652 [00:00<?, ? examples/s]

Map:   0%|          | 0/98 [00:00<?, ? examples/s]

Map:   0%|          | 0/69 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
def new_model_init():
    print("Initializing new model")
    return AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    )

trainer = Trainer(
    model_init=new_model_init,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=410, training_loss=0.08753984995731494, metrics={'train_runtime': 294.4971, 'train_samples_per_second': 22.139, 'train_steps_per_second': 1.392, 'total_flos': 555485347584000.0, 'train_loss': 0.08753984995731494, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.13793784379959106, 'eval_f1_micro': 0.6962025316455697, 'eval_f1_macro': 0.3515242165242165, 'eval_accuracy': 0.5217391304347826, 'eval_precision': 0.43115384615384617, 'eval_recall': 0.3203443223443223, 'eval_f1_label_0': 0.4, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.875, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.2222222222222222, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.75, 'eval_f1_label_7': 0.6923076923076923, 'eval_f1_label_8': 0.9333333333333333, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.8, 'eval_f1_label_13': 0.6, 'eval_f1_label_14': 0.0}

## 1.4 Europe plus Germany

### 1.4.1 Volltext

In [ ]:
# df_full_comp = df_full.drop(columns='Language')

In [ ]:
# df_full_comp.head(3)

In [ ]:
# # Define the text column and extract the label columns
# text_col = 'Headline_GER'
# label_cols = [col for col in df_full_comp.columns if col != text_col]

In [ ]:
# Y = df_full_comp[label_cols].values

# # FIRST SPLIT: 80% Train, 20% Rest
# msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
# train_idx, rest_idx = next(msss1.split(df_full_comp, Y))

# train_df = df_full_comp.iloc[train_idx].copy()
# rest_df = df_full_comp.iloc[rest_idx].copy()
# Y_rest = Y[rest_idx]

# # SECOND SPLIT: Split Rest into 12% Dev / 8% Test
# msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
# dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

# dev_df = rest_df.iloc[dev_sub_idx].copy()
# test_df = rest_df.iloc[test_sub_idx].copy()

# # View
# print(f"Train size: {len(train_df)}")
# print(f"Dev size:   {len(dev_df)}")
# print(f"Test size:  {len(test_df)}")

In [ ]:
# # Convert individual binary columns into a single float list per row
# for split_df in [train_df, dev_df, test_df]:
#     split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# # Create  DatasetDict
# dataset = DatasetDict({
#     'train': Dataset.from_pandas(train_df, preserve_index=False),
#     'dev': Dataset.from_pandas(dev_df, preserve_index=False),
#     'test': Dataset.from_pandas(test_df, preserve_index=False)
# })

In [ ]:
# # Varying Hyerparameters
# tokenized_datasets = dataset.map(tokenize_function, batched=True)
# num_labels = len(label_cols)
# config.num_labels = num_labels

In [ ]:
# # Load the model with the modified configuration
# def new_model_init():
#     print("Initializing new model")
#     return AutoModelForSequenceClassification.from_pretrained(
#         model_id,
#         config=config
#     )

# trainer = Trainer(
#     model_init=new_model_init,
#     args=training_args,
#     train_dataset=tokenized_datasets["train"],
#     eval_dataset=tokenized_datasets["dev"],
#     compute_metrics=compute_metrics
# )

In [ ]:
# # Execute the training loop
# trainer.train()

In [ ]:
# # Final evaluation against the unseen test set
# print("\n--- Final Test Set Evaluation ---")
# test_results = trainer.evaluate(tokenized_datasets["test"])
# print(test_results)

### 1.4.2 Titel

In [ ]:
# df_LLM_comp = df_LLM.drop(columns=[
#     'Language',
#     # Labels
#     'Quality of life',
#     'Capacity and resources',
#     'Fairness and equality',
#     'Public opinion',
#     'Cultural identity',
#     'Policy prescription and evaluation'])

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_LLM-EURplus",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_eur_plus.columns if col != text_col]

In [ ]:
Y = df_LLM_eur_plus[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_idx, rest_idx = next(msss1.split(df_LLM_eur_plus, Y))

train_df = df_LLM_eur_plus.iloc[train_idx].copy()
rest_df = df_LLM_eur_plus.iloc[rest_idx].copy()
Y_rest = Y[rest_idx]

# SECOND SPLIT: Split Rest into 12% Dev / 8% Test
msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

dev_df = rest_df.iloc[dev_sub_idx].copy()
test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 791
Dev size:   124
Test size:  81

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/791 [00:00<?, ? examples/s]

Map:   0%|          | 0/124 [00:00<?, ? examples/s]

Map:   0%|          | 0/81 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
def new_model_init():
    print("Initializing new model")
    return AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    )

trainer = Trainer(
    model_init=new_model_init,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=500, training_loss=0.08517691004276276, metrics={'train_runtime': 318.8129, 'train_samples_per_second': 24.811, 'train_steps_per_second': 1.568, 'total_flos': 673909371072000.0, 'train_loss': 0.08517691004276276, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.14519715309143066, 'eval_f1_micro': 0.6480446927374302, 'eval_f1_macro': 0.3773169096698509, 'eval_accuracy': 0.41975308641975306, 'eval_precision': 0.49193162393162393, 'eval_recall': 0.3194078144078144, 'eval_f1_label_0': 0.5, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.8571428571428571, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.4444444444444444, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.7692307692307693, 'eval_f1_label_7': 0.6428571428571429, 'eval_f1_label_8': 0.8235294117647058, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.7058823529411765, 'eval_f1_label_13': 0.6666666666666666, 'eval_f1_label_14': 0.25}

## 1.5 Europe & MFC

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_LLM-MFC",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_eur_mfc.columns if col != text_col]

In [ ]:
Y = df_LLM_eur_mfc[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_idx, rest_idx = next(msss1.split(df_LLM_eur_mfc, Y))

train_df = df_LLM_eur_mfc.iloc[train_idx].copy()
rest_df = df_LLM_eur_mfc.iloc[rest_idx].copy()
Y_rest = Y[rest_idx]

# SECOND SPLIT: Split Rest into 12% Dev / 8% Test
msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

dev_df = rest_df.iloc[dev_sub_idx].copy()
test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 1818
Dev size:   274
Test size:  187

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/1818 [00:00<?, ? examples/s]

Map:   0%|          | 0/274 [00:00<?, ? examples/s]

Map:   0%|          | 0/187 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
def new_model_init():
    print("Initializing new model")
    return AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    )

trainer = Trainer(
    model_init=new_model_init,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1140, training_loss=0.0508725603813665, metrics={'train_runtime': 624.016, 'train_samples_per_second': 29.134, 'train_steps_per_second': 1.827, 'total_flos': 1548883990656000.0, 'train_loss': 0.0508725603813665, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.10682888329029083, 'eval_f1_micro': 0.7616580310880829, 'eval_f1_macro': 0.5290142551489467, 'eval_accuracy': 0.6470588235294118, 'eval_precision': 0.652269296607532, 'eval_recall': 0.4741773132017035, 'eval_f1_label_0': 0.7692307692307693, 'eval_f1_label_1': 0.8421052631578947, 'eval_f1_label_2': 0.75, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.8, 'eval_f1_label_5': 0.7857142857142857, 'eval_f1_label_6': 0.5333333333333333, 'eval_f1_label_7': 0.8148148148148148, 'eval_f1_label_8': 0.75, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.8709677419354839, 'eval_f1_label_13': 0.7333333333333333, 'eval_f1_label_14': 0.2857142857142857}

## 1.6 Europe & CHN

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_LLM-CHN",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_eur_chn.columns if col != text_col]

In [ ]:
Y = df_LLM_eur_chn[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_idx, rest_idx = next(msss1.split(df_LLM_eur_chn, Y))

train_df = df_LLM_eur_chn.iloc[train_idx].copy()
rest_df = df_LLM_eur_chn.iloc[rest_idx].copy()
Y_rest = Y[rest_idx]

# SECOND SPLIT: Split Rest into 12% Dev / 8% Test
msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

dev_df = rest_df.iloc[dev_sub_idx].copy()
test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 1032
Dev size:   166
Test size:  109

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/1032 [00:00<?, ? examples/s]

Map:   0%|          | 0/166 [00:00<?, ? examples/s]

Map:   0%|          | 0/109 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
def new_model_init():
    print("Initializing new model")
    return AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    )

trainer = Trainer(
    model_init=new_model_init,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=650, training_loss=0.08043755879768959, metrics={'train_runtime': 391.0005, 'train_samples_per_second': 26.394, 'train_steps_per_second': 1.662, 'total_flos': 879234476544000.0, 'train_loss': 0.08043755879768959, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.16469259560108185, 'eval_f1_micro': 0.65625, 'eval_f1_macro': 0.40276720767633417, 'eval_accuracy': 0.3853211009174312, 'eval_precision': 0.5418054248489031, 'eval_recall': 0.361783350748868, 'eval_f1_label_0': 0.46153846153846156, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.7058823529411765, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.46153846153846156, 'eval_f1_label_5': 0.2222222222222222, 'eval_f1_label_6': 0.7, 'eval_f1_label_7': 0.7906976744186046, 'eval_f1_label_8': 0.9285714285714286, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.7346938775510204, 'eval_f1_label_13': 0.6363636363636364, 'eval_f1_label_14': 0.4}

## 1.7 Complete Data

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_LLM-comp",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_comp.columns if col != text_col]

In [ ]:
Y = df_LLM_comp[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_idx, rest_idx = next(msss1.split(df_LLM_comp, Y))

train_df = df_LLM_comp.iloc[train_idx].copy()
rest_df = df_LLM_comp.iloc[rest_idx].copy()
Y_rest = Y[rest_idx]

# SECOND SPLIT: Split Rest into 12% Dev / 8% Test
msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

dev_df = rest_df.iloc[dev_sub_idx].copy()
test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 2065
Dev size:   320
Test size:  205

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/2065 [00:00<?, ? examples/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

Map:   0%|          | 0/205 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
def new_model_init():
    print("Initializing new model")
    return AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    )

trainer = Trainer(
    model_init=new_model_init,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Initializing new model

model.safetensors: reconstructing file:   0%|          |  0.00B /  635MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.weight    | UNEXPECTED |
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Initializing new model

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.weight    | UNEXPECTED |
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1300, training_loss=0.05277860501637826, metrics={'train_runtime': 800.0738, 'train_samples_per_second': 25.81, 'train_steps_per_second': 1.625, 'total_flos': 1759320924480000.0, 'train_loss': 0.05277860501637826, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.1253933161497116, 'eval_f1_micro': 0.7155555555555555, 'eval_f1_macro': 0.532111986022847, 'eval_accuracy': 0.5707317073170731, 'eval_precision': 0.6243492095666009, 'eval_recall': 0.4875316588072343, 'eval_f1_label_0': 0.7586206896551724, 'eval_f1_label_1': 0.7777777777777778, 'eval_f1_label_2': 0.8181818181818182, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.8641975308641975, 'eval_f1_label_5': 0.7906976744186046, 'eval_f1_label_6': 0.5833333333333334, 'eval_f1_label_7': 0.7441860465116279, 'eval_f1_label_8': 0.72, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.5, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.711864406779661, 'eval_f1_label_13': 0.5128205128205128, 'eval_f1_label_14': 0.2}

In [ ]:
print("Best checkpoint:", trainer.state.best_model_checkpoint)
print("Best metric:", trainer.state.best_metric)

Best checkpoint: ./modern_gbert_finetuned_LLM-comp/checkpoint-520
Best metric: 0.5101724488202012

In [ ]:
# login to huggingface
from huggingface_hub import login

login()

In [ ]:
# Save the best model and tokenizer to hugginface
trainer.model.push_to_hub("GER_frame-detect_mgbert134M")
tokenizer.push_to_hub("GER_frame-detect_mgbert134M")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...g_rg4rg/model.safetensors:   0%|          |  556kB /  539MB

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/nameless-0/GER_frame-detect_mgbert134M/commit/b54c545326f3639bf431941778e55429ad6db5b7', commit_message='Upload tokenizer', commit_description='', oid='b54c545326f3639bf431941778e55429ad6db5b7', pr_url=None, repo_url=RepoUrl('https://huggingface.co/nameless-0/GER_frame-detect_mgbert134M', endpoint='https://huggingface.co', repo_type='model', repo_id='nameless-0/GER_frame-detect_mgbert134M'), pr_revision=None, pr_num=None)

# 2 Approximate Transfer

## 2.1 Train mit ALL minus GER & CHN & MFC (=EU minus GER)

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_Transfer-AllMin_GER-MFC-CHN",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_ex_GerChnMFC.columns if col != text_col]

In [ ]:
Y_allmin_GerChnMFC = df_LLM_ex_GerChnMFC[label_cols].values
Y_ger = df_LLM_ger[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
## COMP
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_eur_idx, rest_eur_idx = next(msss1.split(df_LLM_ex_GerChnMFC, Y_allmin_GerChnMFC))
## GERMANY
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_ger_idx, test_ger_idx = next(msss1.split(df_LLM_ger, Y_ger))

train_df = df_LLM_ex_GerChnMFC.iloc[train_eur_idx].copy()
dev_df = df_LLM_ger.iloc[dev_ger_idx].copy()
test_df = df_LLM_ger.iloc[test_ger_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 652
Dev size:   106
Test size:  71

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/652 [00:00<?, ? examples/s]

Map:   0%|          | 0/106 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
trainer = Trainer(
    model_init=lambda: AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    ),
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=410, training_loss=0.08753984995731494, metrics={'train_runtime': 268.43, 'train_samples_per_second': 24.289, 'train_steps_per_second': 1.527, 'total_flos': 555485347584000.0, 'train_loss': 0.08753984995731494, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.3434238135814667, 'eval_f1_micro': 0.3795620437956204, 'eval_f1_macro': 0.20868686868686867, 'eval_accuracy': 0.2535211267605634, 'eval_precision': 0.1932900432900433, 'eval_recall': 0.23240740740740737, 'eval_f1_label_0': 0.5, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.5, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.0, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.0, 'eval_f1_label_7': 0.6666666666666666, 'eval_f1_label_8': 0.7, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.4, 'eval_f1_label_13': 0.36363636363636365, 'eval_f1_label_14': 0.0}

## 2.2 Train mit ALL minus GER & MFC

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_Transfer-AllMin_GER-MFC",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_ex_GerMFC.columns if col != text_col]

In [ ]:
Y_allmin_GerMFC = df_LLM_ex_GerMFC[label_cols].values
Y_ger = df_LLM_ger[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
## COMP
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_eur_idx, rest_eur_idx = next(msss1.split(df_LLM_ex_GerMFC, Y_allmin_GerMFC))
## GERMANY
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_ger_idx, test_ger_idx = next(msss1.split(df_LLM_ger, Y_ger))

train_df = df_LLM_ex_GerMFC.iloc[train_eur_idx].copy()
dev_df = df_LLM_ger.iloc[dev_ger_idx].copy()
test_df = df_LLM_ger.iloc[test_ger_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 894
Dev size:   106
Test size:  71

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/894 [00:00<?, ? examples/s]

Map:   0%|          | 0/106 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
trainer = Trainer(
    model_init=lambda: AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    ),
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=560, training_loss=0.0837097958794662, metrics={'train_runtime': 352.2313, 'train_samples_per_second': 25.381, 'train_steps_per_second': 1.59, 'total_flos': 761662424448000.0, 'train_loss': 0.0837097958794662, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.31677576899528503, 'eval_f1_micro': 0.4195804195804196, 'eval_f1_macro': 0.235004255004255, 'eval_accuracy': 0.28169014084507044, 'eval_precision': 0.2314285714285714, 'eval_recall': 0.262037037037037, 'eval_f1_label_0': 0.4444444444444444, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.6666666666666666, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.0, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.0, 'eval_f1_label_7': 0.6923076923076923, 'eval_f1_label_8': 0.7, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.47619047619047616, 'eval_f1_label_13': 0.5454545454545454, 'eval_f1_label_14': 0.0}

## 2.3 Train mit ALL minus GER & CHN

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_Transfer-AllMin_GER-CHN",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_ex_GerChn.columns if col != text_col]

In [ ]:
Y_allmin_GerChn = df_LLM_ex_GerChn[label_cols].values
Y_ger = df_LLM_ger[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
## COMP
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_eur_idx, rest_eur_idx = next(msss1.split(df_LLM_ex_GerChn, Y_allmin_GerChn))
## GERMANY
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_ger_idx, test_ger_idx = next(msss1.split(df_LLM_ger, Y_ger))

train_df = df_LLM_ex_GerChn.iloc[train_eur_idx].copy()
dev_df = df_LLM_ger.iloc[dev_ger_idx].copy()
test_df = df_LLM_ger.iloc[test_ger_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 1676
Dev size:   106
Test size:  71

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/1676 [00:00<?, ? examples/s]

Map:   0%|          | 0/106 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
trainer = Trainer(
    model_init=lambda: AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    ),
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1050, training_loss=0.049359238303843, metrics={'train_runtime': 618.3473, 'train_samples_per_second': 27.105, 'train_steps_per_second': 1.698, 'total_flos': 1427904052992000.0, 'train_loss': 0.049359238303843, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.36235910654067993, 'eval_f1_micro': 0.39436619718309857, 'eval_f1_macro': 0.23236647173489278, 'eval_accuracy': 0.2676056338028169, 'eval_precision': 0.23789627039627043, 'eval_recall': 0.24537037037037035, 'eval_f1_label_0': 0.5, 'eval_f1_label_1': 0.0, 'eval_f1_label_2': 0.6666666666666666, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.0, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.0, 'eval_f1_label_7': 0.72, 'eval_f1_label_8': 0.7777777777777778, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.4, 'eval_f1_label_13': 0.42105263157894735, 'eval_f1_label_14': 0.0}

## 2.4 Train mit All minus GER, Test auf Germany

In [ ]:
# Application-specific arguments
application_training_args = {
    "output_dir": f"./modern_gbert_finetuned_Transfer-AllMin_GER",
}

# Combine them
training_args = TrainingArguments(
    **general_training_args,
    **application_training_args,
)

In [ ]:
# Define the text column and extract the label columns
text_col = 'Headline_GER'
label_cols = [col for col in df_LLM_ex_Ger.columns if col != text_col]

In [ ]:
Y_allmin_Ger = df_LLM_ex_Ger[label_cols].values
Y_ger = df_LLM_ger[label_cols].values

# FIRST SPLIT: 80% Train, 20% Rest
## COMP
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.20, random_state=42)
train_eur_idx, rest_eur_idx = next(msss1.split(df_LLM_ex_Ger, Y_allmin_Ger))
## GERMANY
msss1 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
dev_ger_idx, test_ger_idx = next(msss1.split(df_LLM_ger, Y_ger))

train_df = df_LLM_ex_Ger.iloc[train_eur_idx].copy()
dev_df = df_LLM_ger.iloc[dev_ger_idx].copy()
test_df = df_LLM_ger.iloc[test_ger_idx].copy()


# rest_df = df_full_ger.iloc[rest_ger_idx].copy()
# Y_rest = Y_ger[rest_ger_idx]

# SECOND SPLIT on GERMANY only: Split Rest into 12% Dev / 8% Test
#msss2 = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.40, random_state=42)
#dev_sub_idx, test_sub_idx = next(msss2.split(rest_df, Y_rest))

#dev_df = rest_df.iloc[dev_sub_idx].copy()
#test_df = rest_df.iloc[test_sub_idx].copy()

# View
print(f"Train size: {len(train_df)}")
print(f"Dev size:   {len(dev_df)}")
print(f"Test size:  {len(test_df)}")

Train size: 1925
Dev size:   106
Test size:  71

In [ ]:
# Convert individual binary columns into a single float list per row
for split_df in [train_df, dev_df, test_df]:
    split_df['labels'] = split_df[label_cols].astype(float).values.tolist()

In [ ]:
# Create  DatasetDict
dataset = DatasetDict({
    'train': Dataset.from_pandas(train_df, preserve_index=False),
    'dev': Dataset.from_pandas(dev_df, preserve_index=False),
    'test': Dataset.from_pandas(test_df, preserve_index=False)
})

In [ ]:
# Varying Hyerparameters
tokenized_datasets = dataset.map(tokenize_function, batched=True)
num_labels = len(label_cols)
config.num_labels = num_labels

Map:   0%|          | 0/1925 [00:00<?, ? examples/s]

Map:   0%|          | 0/106 [00:00<?, ? examples/s]

Map:   0%|          | 0/71 [00:00<?, ? examples/s]

In [ ]:
# Load the model with the modified configuration
trainer = Trainer(
    model_init=lambda: AutoModelForSequenceClassification.from_pretrained(
        model_id,
        config=config
    ),
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["dev"],
    compute_metrics=compute_metrics
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
# Execute the training loop
trainer.train()

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: LSX-UniWue/ModernGBERT_134M
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
decoder.weight    | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1210, training_loss=0.051422107435208704, metrics={'train_runtime': 692.9493, 'train_samples_per_second': 27.78, 'train_steps_per_second': 1.746, 'total_flos': 1640044929600000.0, 'train_loss': 0.051422107435208704, 'epoch': 10.0})

In [ ]:
# Final evaluation against the unseen test set
print("\n--- Final Test Set Evaluation ---")
test_results = trainer.evaluate(tokenized_datasets["test"])
print(test_results)

--- Final Test Set Evaluation ---

{'eval_loss': 0.32884377241134644, 'eval_f1_micro': 0.40816326530612246, 'eval_f1_macro': 0.2558177117000646, 'eval_accuracy': 0.28169014084507044, 'eval_precision': 0.2599867724867725, 'eval_recall': 0.28703703703703703, 'eval_f1_label_0': 0.5714285714285714, 'eval_f1_label_1': 0.25, 'eval_f1_label_2': 0.6666666666666666, 'eval_f1_label_3': 0.0, 'eval_f1_label_4': 0.0, 'eval_f1_label_5': 0.0, 'eval_f1_label_6': 0.0, 'eval_f1_label_7': 0.6923076923076923, 'eval_f1_label_8': 0.8235294117647058, 'eval_f1_label_9': 0.0, 'eval_f1_label_10': 0.0, 'eval_f1_label_11': 0.0, 'eval_f1_label_12': 0.4166666666666667, 'eval_f1_label_13': 0.4166666666666667, 'eval_f1_label_14': 0.0}